name: Terraform + Ansible Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      # -------------------------
      # Terraform
      # -------------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init 

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve -lock=false

      # -------------------------
      # Generate Ansible Inventory
      # -------------------------
      - name: Generate Ansible inventory
        working-directory: terraform
        run: |
          JAVA_IP=$(terraform output -raw java_node_ip)
          NGINX_IP=$(terraform output -raw nginx_node_ip)

          cat <<EOF > ../ansible/hosts
          [java-node]
          $JAVA_IP 

          [nginx-node]
          $NGINX_IP 
          EOF

      # -------------------------
      # Ansible
      # -------------------------
      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible Playbook
        run: |
          echo "${{ secrets.AWS_SSH_KEY }}" > /tmp/key.pem
          chmod 400 /tmp/key.pem

      - name: Run Ansible Playbook
        working-directory: ansible
        run: |
          ansible-playbook -i hosts playbook.yml -vvvvv
          rm /tmp/key.pem

      - name: Run Ansible Playbook
        run:
          rm /tmp/key.pem

