name: Terraform + Ansible Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      # -------------------------
      # SSH Key for Ansible
      # -------------------------
      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/key.pem
          chmod 400 /tmp/key.pem

      # -------------------------
      # Terraform
      # -------------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init || terraform fmt || terraform validate

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

      # -------------------------
      # Generate Ansible Inventory
      # -------------------------
      - name: Generate Ansible inventory
        working-directory: terraform
        run: |
          JAVA_IP=$(terraform output -raw java_node_ip)
          NGINX_IP=$(terraform output -raw nginx_node_ip)

          cat <<EOF > ../ansible/inventory.ini
          [java-node]
          $FRONTEND_IP 

          [nginx-node]
          $BACKEND_IP 
          EOF

      # -------------------------
      # Ansible
      # -------------------------
      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible Playbook
        working-directory: ansible
        run: |
          ansible-playbook -i hosts deploy.yml
